import type { Metadata } from "next";
import { Inter, Roboto, Poppins, Space_Grotesk,  } from "next/font/google";
import "./globals.css";

const inter = Inter({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const roboto = Roboto({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});



export const metadata: Metadata = {
  title: "Personal Chatbot",
  description: "Generated by Tanmay Shil",
  keywords: ["Personal Chatbot", "Tanmay Shil", "AI Chatbot", "Next.js", "TypeScript", "Tailwind CSS", "shadcn/ui", "Custom Hook", "Groq Free AI API", "Axios", "English Mode", "Bengali Mode", "Mobile Friendly UI"],
  authors: [
    {
      name: "Tanmay Shil",
      url: "https://tanmayshil.com",
    },
  ],
  publisher: "Tanmay Shil",
  openGraph: {
    title: "Personal Chatbot",
    description: "Generated by Tanmay Shil",
    type: "website",
    locale: "en",
    siteName: "Personal Chatbot",
    images: [
      {
        url: "/chatbot.png",
        width: 1200,
        height: 630,
        alt: "Personal Chatbot",
      },
    ],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${roboto.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
